### ISSUE TITLE
`recursive use of an object detected which would lead to unsafe aliasing in rust`

### ISSUE THREAD

**Issue by Skn0tt** [worker-tools/html-rewriter#6]
Hi! I'm running html-rewriter in production on a few bigger sites, and we're seeing a few instances of crashes with the error `Error: recursive use of an object detected which would lead to unsafe aliasing in rust`. We're running html-rewriter in Deno, and are unsure what exactly is causing the issue. We strongly suspect it's related to html-rewriter though. Does this ring a bell for y'all?

**Comment by qwtel** [comment]
It does not ring a bell, but I've suspected that this module might run into issues under load. 

I've updated this module with the latest versions of lol-html and wasm-pack, perhaps mit makes a difference, but there's not much I can do beyond that.

**Comment by Skn0tt** [comment]
Thanks for updating! It's good to know that this error under load doesn't sound entirely improbable to you. Let's hope that the upgrade helps. Thanks for your help Florian :D I'll upgrade the module on our end, and reopen the issue if I still see it happening. Maybe i'll need to dig into lol-html and wasm-pack in that case.

**Comment by qwtel** [comment]
> Maybe i'll need to dig into lol-html and wasm-pack in that case.

Yes, that's likely. It's doing some wasm stack magic under the hood (key word "asyncify"), which is known for performance overhead, and what it means for concurrent interactions with the wasm machine I do not know.
